---
title: "R markdown"
author: "Victor L. Jardim"
date: "2022-11-30"
output: 
  rmdformats::readthedown:
    code_folding: "show"
    highlight: "tango"
    lightbox: TRUE
    gallery: TRUE
    thumbnails: FALSE
    toc_depth: 6
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise 3.

Using the function to read, join and select only the Ursidae species from the wildfinder database "read_wildfinder", let's load the full table

```{r cars}

final_table <- read_wildfinder()
```

## Let's take a look at the data

Count the number of ecoregions where you can find each species

```{r pressure, echo=TRUE}
res <- list()
for (i in final_table$sci_name){
  res[[i]] <- length(unique(final_table$ecoregion[final_table$sci_name == i]))
}

sp_ecoreg <- as.data.frame(t(as.data.frame(res))) 
sp_ecoreg <- sp_ecoreg |>
  tibble::rownames_to_column(var = "species") |> 
  dplyr::rename(n_ecoregions = V1)
sp_ecoreg$species <- gsub("\\.", " ", sp_ecoreg$species)

```

## Let's show that

```{r}

ggplot2::ggplot(sp_ecoreg, ggplot2::aes(x = species, y = n_ecoregions, fill = species))+
  ggplot2::geom_bar(stat = "identity")+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::labs(x = "Species", y = "Number of ecoregions")+
  ggplot2::theme(legend.position = "bottom", axis.text.x = ggplot2::element_text(angle = 45, vjust = 0.4))
```
